### ISSUE TITLE
Compilation error when using plan-only mode

### ISSUE THREAD

**Issue by bradley-campbell** [hashicorp/terraform-cdk-action#2]
I'm running into an issue when trying to run the cdk action in `plan-only` mode.

```
Error: 022-08-01T15:23:24.626] [ERROR] default - TSError: ⨯ Unable to compile TypeScript:
Error: src/stacks/baseStack.ts(10,27): error TS2307: Cannot find module '../../.gen/modules/labelNull' or its corresponding type declarations.
```

From what I understand from the source code, it seems as though `cdktf get` is not run by the action and therefore the required modules are not compiled into JSII. 

Is there a way to configure the action to run `cdktf get` before running a plan or deploy?

**Comment by DanielMSchmidt** [comment]
Sorry for the late reply! You would need to do get as an extra step before the action is invoked. I'll adjust the examples to include get specifically (I normally have get set up as a postinstall command)

**Comment by bradley-campbell** [comment]
I tried your suggestion and it's working for me! Thanks for the reply
