### ISSUE TITLE
exceeded a secondary rate limit

### ISSUE THREAD

**Issue by oliverbrixel** [hashicorp/terraform-cdk-action#33]
We regularly get the error "Error: You have exceeded a secondary rate limit. Please wait a few minutes before you try again." 

The following can be seen in the log:

```
...
mything  Created speculative Terraform Cloud run: <url>
mything  Speculative Terraform Cloud run done

mything  Speculative Terraform Cloud run done
mything  Getting plan output

mything  Getting plan output
mything  Fetching Terraform Cloud outputs

mything  Fetching Terraform Cloud outputs

No outputs found.


No outputs found.
Error: You have exceeded a secondary rate limit. Please wait a few minutes before you try again.
```

What can be done to not get the error?

Our configuration:

inside the jobs:
          terraformVersion: 1.4.2
          cdktfVersion: 0.15.5

on terraform cloud in the workspaces:
        terraformVersion: 1.4.2

**Comment by ansgarm** [comment]
Hi @oliverbrixel 👋

Are you passing a `githubToken`? The error message looks like it could come from the Github API when trying to create a comment – Is that token maybe used by multiple Github Actions running in parallel?

**Comment by oliverbrixel** [comment]
Hi @ansgarm Yes, we are passing an automatically generated `githubToken` and we are getting the comments in the timeline. What we also do is that we run our stacks/workspaces in sequence from one repository. Can this be a problem? In our configuration we a pull requests trigger a `plan-only` and during are merging into `main` than we have an `auto-approve-apply`. So, there are potentially parallel runs. We will investigate whether the errors occur in such a situation.

**Comment by oliverbrixel** [comment]
So, I tested it. We are getting the error with only one running github workflow.

**Comment by oliverbrixel** [comment]
I added the information about the versions we are using to the comment in the ticket description.

**Comment by ansgarm** [comment]
Out of curiosity: How many stacks does your CDKTF project have? I could see this becoming a common problem for CDKTF projects with lots of stacks as they would get individual comments posted.
So we might actually improve this by only adding a single comment or updating an existing comment with information about other stacks as they finish (I suspect that this would have a higher secondary rate limit compared to creating new comments).

**Comment by oliverbrixel** [comment]
Hello @ansgarm, at the moment we have 3 stacks in one repository. These stacks are all applied one after the other. 

The suggestion to add the response headers is good. It would definitely help to isolate the error.
