### ISSUE TITLE
Support for setting the 'parallelism' flag

### ISSUE THREAD

**Issue by sbkg0002** [hashicorp/terraform-cdk-action#34]
Hi,

Please make the `parallelism` [feature from cdktf](https://developer.hashicorp.com/terraform/cdktf/cli-reference/commands#deploy) configurable via the Action.

Thanks in advance!
Johan

**Comment by xiehan** [comment]
Thanks for the suggestion! We agree this is a nice feature to have. Unfortunately it's not something we'll have capacity to work on soon, but we welcome any community contributions.

**Comment by Maed223** [comment]
Hey there 👋

After some discussion we don't think this addition would make sense– as the action is intended to be limited to a single stack.

While you could pass `*` as the stack name and use multi-stack deployments, we don't currently support all the complexities of doing accurate plans across multiple dependent workspaces within the action.
